# Generated by Django 4.1 on 2022-08-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product_remark_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('iPhone', 'iPhone'), ('Android', 'Android'), ('Macbook', 'Macbook'), ('GraphicCards', 'Graphic Cards'), ('Headphones', 'Headphones'), ('SmartHome', 'Smart Home'), ('NoCategory ', 'No Category')], default='NoCategory', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='startingBid',
            field=models.IntegerField(),
        ),
    ]
