# Generated by Django 4.1 on 2022-08-11 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remark',
            name='product',
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Remark',
        ),
    ]
