# Generated by Django 4.1 on 2022-08-12 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_remark_product_alter_remark_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
